name: Repo R2S 21.02 Build
on:
  schedule:
    - cron: '30 21 */3 * *'
  workflow_dispatch:
    #ref: refs/heads/main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/7504355/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.workflow_token }}" \
            -d '{"ref": "main"}'
