name: Update

on: 
  #repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 00 20 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: 设置帐户
        run: git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

      - name: 复制
        run: |
          svn export https://github.com/klever1988/nanopi-openwrt/trunk/ new
        
      - name: 整理
        run: | 
          cp -rf new/*.seed ./
          cp -rf new/scripts/merge_files.sh ./scripts/
          cp -rf new/scripts/merge_packages.sh ./scripts/
          cp -rf new/scripts/patches.sh ./scripts/
          rm -rf new
         
      - name: 添加文件到暂存区
        run: git add .
             
      - name: 暂存区全部文件替换工作区
        run: git checkout .

      - name: 提交
        run: git commit -am 'Update'

      - name: 更新
        run: git push
