name: update

on: 
  workflow_dispatch:
  schedule:
    - cron: 00 20 * * *

jobs:
  build_packages:
    name: update
    runs-on: ubuntu-20.04
    
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: 设置帐户
        run: git config --global user.name '00575' && git config --global user.email 'xixiaaijia@gmail.com'

      - name: 拉取
        run: |
          svn export https://github.com/klever1988/nanopi-openwrt/trunk/ new
          wget -O scripts/kernel https://github.com/immortalwrt/immortalwrt/raw/openwrt-18.06-k5.4/include/kernel-version.mk
        
      - name: 复制整理
        run: | 
          cp -rf new/*.seed ./
          cp -rf new/scripts/merge_files.sh ./scripts/
          cp -rf new/scripts/merge_packages.sh ./scripts/
          cp -rf new/scripts/patches.sh ./scripts/
          rm -rf new
          
      - name: 修改文件
        run: | 
          sed -i 's?klever1988/nanopi-openwrt?00575/Nanopi?g' scripts/patches.sh
          sed -i 's/openwrt2020/argon/g' scripts/patches.sh
         
      - name: 添加文件到暂存区
        run: git add .
             
      - name: 暂存区全部文件替换工作区
        run: git checkout .

      - name: 提交
        run: git commit -am 'update$(TZ='Asia/Shanghai' date +-%m.%d)'

      - name: 更新
        run: git push

  Repo-Dispatcher:
    needs: build_packages
    name: Repo-Dispatcher
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        device: [r1p, r1s, r1s-h3, r2c, r2s, r4s, x86]
    
    steps:
      - name: Trigger Compile
        run: |
          if [ '${{ matrix.device }}' = 'r1s' ]; then
            branch='18.06';
          else
            branch='master';
          fi
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.workflow_token }}" \
          -d '{"event_type": "${{ matrix.device }}", "client_payload": {"branch": "'$branch'", "device": "${{ matrix.device }}", "package_clean": "${{ github.event.inputs.package_clean }}" }}'
