name: Update-test

env:
  REPO_URL: https://github.com/00575/file
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 00 18 * * *

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: Trigger Compile
      run: |
        curl \
        -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/12635960/dispatches \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.workflow_token }}" \
        -d '{"package_clean":"true"}'
