name: Update Checker

on: 
  workflow_dispatch:
    inputs:
      package_clean:
        description: 'check to make clean package'
        default: 'true'
        required: true
  schedule:
    - cron: 00 17 * * *

env:
  TZ: Asia/Shanghai

jobs:
  update:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
 
      - name: 设置当前的日期
        id: date
        run: |
          sudo timedatectl set-timezone "$TZ"
          #echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
          echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
 
      - name: 设置帐户
        run: |
          #git config --local user.name "GitHub Action" && git config --local user.email "action@github.com"
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
          
      - name: 下载并修改文件
        run: | 
          git clone -b master --single-branch https://github.com/klever1988/nanopi-openwrt new
          cp -rf new/*.seed ./
          cp -rf new/scripts/*.sh ./scripts/
          cp -rf new/files/etc/* ./files/etc/
          cp -rf new/patches/* ./patches/
          sed -i 's?klever1988/nanopi-openwrt?00575/Nanopi?g' scripts/patches.sh
          sed -i 's/openwrt2020/argon/g' scripts/patches.sh
          rm -rf new
          rm -rf /scripts/autoupdate-offline.sh
          wget -qO scripts/kernel https://github.com/coolsnowwolf/lede/raw/master/include/kernel-5.15
          sed -i 's?klever1988/nanopi-openwrt?00575/Nanopi?g' scripts/autoupdate.sh
          sed -i 's?klever1988/nanopi-openwrt?00575/Nanopi?g' scripts/autoupdate-bash.sh
          #sed -i '/192.168.2.1/a\cp -f $GITHUB_WORKSPACE/assets/banner /package/base-files/files/etc/banner' scripts/patches.sh
          
      - name: 添加文件到暂存区
        run: git add .
             
      - name: 暂存区全部文件替换工作区
        run: git checkout .

      - name: 提交
        run: git commit -am 'update-${{ env.date }}'

      - name: 同步
        run: git push

      - name: 删除工作流
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 10

  Repo-Dispatcher:
    needs: update
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device: [r1p, r1s, r1s-h3, r2c, r2s, r4s, x86]
    steps:
      - name: Trigger Compile
        run: |
          branch='master';
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.workflow_token }}" \
          -d '{"event_type": "${{ matrix.device }}", "client_payload": {"branch": "'$branch'", "device": "${{ matrix.device }}", "package_clean": "${{ github.event.inputs.package_clean }}" }}'
